#! /bin/sh

case "$1" in
	start)
		echo "Starting aesd socket-server"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -d
		;;
	stop)
		echo "Stopping aesd socket-server"
		start-stop-deamon -K -n aesdsocket
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0